services:
  rabbitmq:
      image: "rabbitmq:3-management"
      environment:
        RABBITMQ_DEFAULT_USER: "user"
        RABBITMQ_DEFAULT_PASS: "password"
      ports:
        - "5672:5672" 
        - "15672:15672"
      volumes:
        - "./rabbitData:/var/lib/rabbitmq"
      healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 30s
        retries: 3
 
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongoData:/data/db