version: '3.3'

services:
  contentautoat:
    image: "marko17/vogicontentautoatapi"
    ports:
      - '80:49156'

    environment:
      - ASPNET_VERSION=6.0.25
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
